### ISSUE TITLE
Increasing the size of the Dots on Nameplates 

### ISSUE THREAD

**Issue by barnowl12312312** [wkrueger/biggerbuffs#1]
Im not sure if this is intended but when increasing the size of the icons for the party frames, this also increases the DoT's and icons over the personal resource bar which results in large black boxes of the icon.

Is this intended? 
![WoWScrnShot_082620_211500](https://user-images.githubusercontent.com/70307642/91765348-adfa4e80-eb8d-11ea-857e-10f916b1e0ee.jpg)

Note: Some debuffs will have the above issue while others dont. It seems to be purely random.
Note: I have been using OmniCC with this addon.

**Comment by wkrueger** [comment]
this was an old issue with the "raid frames fix" addon, doesnt happen anymore
