### ISSUE TITLE
I can't get more than 3 hots as resto druid

### ISSUE THREAD

**Issue by palla89** [wkrueger/biggerbuffs#2]
Hi! I used your awesome addon in Shadowlands and was working perfectly for me, but I can't get it to work in Dragonflight.. can you help me? I just  would love to see more than three hots at times.. When I open the config it just ignores me. 

Some screeenshots:
here i have 4 hots:

![image](https://user-images.githubusercontent.com/12301205/200139536-308eb79e-aefb-4dac-bdb3-1341c8a9dfe5.png)

and this is my config screen
![image](https://user-images.githubusercontent.com/12301205/200139541-02453da3-d436-4b57-bc47-65f027d61f0d.png)

Can you help me? :(

**Comment by chrisafl** [comment]
Having the same issue, it seems like the github version doesn't match the curseforge version also

**Comment by wkrueger** [comment]
It's been disabled on purpose as a quick fix because this was completely breaking the frames in 10.0.0.

I've been mostly commenting on curseforge..

I've pushed the lastest version, thx for reminder.

**Comment by chrisafl** [comment]
That makes sense, all of the similar addons are having the same problem. The main similar addon to this to my knowledge is BigDebuffs, but I prefer this addon because all I want it for is to show more HoTs while healing which this addon should do perfectly once the taint issue is resolved.

Thank you for all of your work on this!

**Comment by wkrueger** [comment]
Yeah I usually use both (they do different things).

I've been not playing on the current weeks, I intend to get more hours on the week before expansion launch.

**Comment by wkrueger** [comment]
Most recent blizzard UI stopped breaking the frames.

Reverting the addon to previous state.
